version: '3.1'

services:
  ghost-prod:
    image: ghost:latest
    ports:
      - "2368:2368"
    environment:
      database__client: mysql
      database__connection__host: mariadb
      database__connection__user: root
      database__connection__password: example
      database__connection__database: ghost_prod
      url: http://localhost:2368
    volumes:
      - ./content:/var/lib/ghost/content
    depends_on:
      - mariadb
    restart: always

  mariadb:
    image: mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: ghost_prod
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: always

volumes:
  mariadb_data:
